org: ciat
app: marlodocumentsredirection
service: app-server-marlo-documents-redirection
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
